// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWYvZ4VHK4wsa1iq4Z5xX2u7AiFmCDEZQ',
    appId: '1:952301726008:web:d9d8d3482b78d57c8439cd',
    messagingSenderId: '952301726008',
    projectId: 'fcmswallet',
    authDomain: 'fcmswallet.firebaseapp.com',
    storageBucket: 'fcmswallet.firebasestorage.app',
    measurementId: 'G-7F4DZ4DTJB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3CsQtBCDyiSGv8k8dh2EXd4NBvrG6Zsw',
    appId: '1:952301726008:android:f85318c27297443f8439cd',
    messagingSenderId: '952301726008',
    projectId: 'fcmswallet',
    storageBucket: 'fcmswallet.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCw0oHYPZ2X6_8PHCy5sPZFpU3QgJZisC4',
    appId: '1:952301726008:ios:cb67bc32342e75148439cd',
    messagingSenderId: '952301726008',
    projectId: 'fcmswallet',
    storageBucket: 'fcmswallet.firebasestorage.app',
    iosBundleId: 'com.example.swalletMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCw0oHYPZ2X6_8PHCy5sPZFpU3QgJZisC4',
    appId: '1:952301726008:ios:cb67bc32342e75148439cd',
    messagingSenderId: '952301726008',
    projectId: 'fcmswallet',
    storageBucket: 'fcmswallet.firebasestorage.app',
    iosBundleId: 'com.example.swalletMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWYvZ4VHK4wsa1iq4Z5xX2u7AiFmCDEZQ',
    appId: '1:952301726008:web:56cad045bf9be5378439cd',
    messagingSenderId: '952301726008',
    projectId: 'fcmswallet',
    authDomain: 'fcmswallet.firebaseapp.com',
    storageBucket: 'fcmswallet.firebasestorage.app',
    measurementId: 'G-4N05JLPKR9',
  );
}
